Upgraded the laborer dependency. The 2.5.15 version appeared to have a typo in its linting rules:   node_modules/laborer/sasslint-rules.js:  "no-color-keyword": 1,
That broke the gulp build with:
   Error: Rule `no-color-keyword` could not be found!

The rule is "no-color-keywords".  This is fixed in the latest version.